#!/bin/sh
set -x

luafile="$(basename $0)"
luafile="${luafile%-gif}"
luafile="demos/lua/${luafile}.lua"

launch_vis() {
  ./lua-music-visualizer \
    --width 1280 \
    --height 720 \
    --fps 30 \
    --samplerate 48000 \
    --channels 2 \
    --bars 20 \
    /dev/zero \
    "${luafile}" \
    "$@"
}
