#!/bin/sh

if [ ! -f "demos/bars" ] ; then
    1>&2 printf "Please run this script from the root of the repo\n"
    1>&2 printf "./demos/bars\n"
    exit 1
fi

. demos/lib/deps
. demos/lib/launch

1>&2 printf "Launching lua-music-visualizer, demo should quit in 10 seconds"

launch_vis ffplay -loglevel error pipe:0


